/* PKMNcaught.js
 * JavaScript file to handle the Pokemon caught
 * Made on 2016-02-25
 * by GeOdin
 * Last modified on 2016-02-27
 *
 *=========================================================
 * This file includes the following variables: *
 *=========================================================
 * pokemonCaught
 */

// variable to check whether a pokemon has been caught (to count caught pokemon for the pokedex)
// 0 = not caught
// 1 = caught
var pokemonCaught = {
	BULBASAUR: 0,
	IVYSAUR: 0,
	VENUSAUR: 0,
	CHARMANDER: 0,
	CHARMELEON: 0,
	CHARIZARD: 0,
	SQUIRTLE: 0,
	WARTORTLE: 0,
	BLASTOISE: 0,
	CATERPIE: 0,
	METAPOD: 0,
	BUTTERFREE: 0,
	WEEDLE: 0,
	KAKUNA: 0,
	BEEDRILL: 0,
	PIDGEY: 0,
	PIDGEOTTO: 0,
	PIDGEOT: 0,
	RATTATA: 0,
	RATICATE: 0,
	SPEAROW: 0,
	FEAROW: 0,
	EKANS: 0,
	ARBOK: 0,
	PIKACHU: 0,
	RAICHU: 0,
	SANDSHREW: 0,
	SANDSLASH: 0,
	NIDORAN_FEMALE: 0,
	NIDORINA: 0,
	NIDOQUEEN: 0,
	NIDORAN_MALE: 0,
	NIDORINO: 0,
	NIDOKING: 0,
	CLEFAIRY: 0,
	CLEFABLE: 0,
	VULPIX: 0,
	NINETALES: 0,
	JIGGLYPUFF: 0,
	WIGGLYTUFF: 0,
	ZUBAT: 0,
	GOLBAT: 0,
	ODDISH: 0,
	GLOOM: 0,
	VILEPLUME: 0,
	PARAS: 0,
	PARASECT: 0,
	VENONAT: 0,
	VENOMOTH: 0,
	DIGLETT: 0,
	DUGTRIO: 0,
	MEOWTH: 0,
	PERSIAN: 0,
	PSYDUCK: 0,
	GOLDUCK: 0,
	MANKEY: 0,
	PRIMEAPE: 0,
	GROWLITHE: 0,
	ARCANINE: 0,
	POLIWAG: 0,
	POLIWHIRL: 0,
	POLIWRATH: 0,
	ABRA: 0,
	KADABRA: 0,
	ALAKAZAM: 0,
	MACHOP: 0,
	MACHOKE: 0,
	MACHAMP: 0,
	BELLSPROUT: 0,
	WEEPINBELL: 0,
	VICTREEBELL: 0,
	TENTACOOL: 0,
	TENTACRUEL: 0,
	GEODUDE: 0,
	GRAVELER: 0,
	GOLEM: 0,
	PONYTA: 0,
	RAPIDASH: 0,
	SLOWPOKE: 0,
	SLOWBRO: 0,
	MAGNEMITE: 0,
	MAGNETON: 0,
	FARFETCH_D: 0,
	DODUO: 0,
	DODRIO: 0,
	SEEL: 0,
	DEWGONG: 0,
	GRIMER: 0,
	MUK: 0,
	SHELLDER: 0,
	CLOYSTER: 0,
	GASTLY: 0,
	HAUNTER: 0,
	GENGAR: 0,
	ONIX: 0,
	DROWZEE: 0,
	HYPNO: 0,
	KRABBY: 0,
	KINGLER: 0,
	VOLTORB: 0,
	ELECTRODE: 0,
	EXEGGCUTE: 0,
	EXEGGUTOR: 0,
	CUBONE: 0,
	MAROWAK: 0,
	HITMONLEE: 0,
	HITMONCHAN: 0,
	LICKITUNG: 0,
	KOFFING: 0,
	WEEZING: 0,
	RHYHORN: 0,
	RHYDON: 0,
	CHANSEY: 0,
	TANGELA: 0,
	KANGASKHAN: 0,
	HORSEA: 0,
	SEADRA: 0,
	GOLDEEN: 0,
	SEAKING: 0,
	STARYU: 0,
	STARMIE: 0,
	MR_MIME: 0,
	SCYTHER: 0,
	JYNX: 0,
	ELECTABUZZ: 0,
	MAGMAR: 0,
	PINSIR: 0,
	TAUROS: 0,
	MAGIKARP: 0,
	GYARADOS: 0,
	LAPRAS: 0,
	DITTO: 0,
	EEVEE: 0,
	VAPOREON: 0,
	JOLTEON: 0,
	FLAREON: 0,
	PORYGON: 0,
	OMANYTE: 0,
	OMASTAR: 0,
	KABUTO: 0,
	KABUTOPS: 0,
	AERODACTYL: 0,
	SNORLAX: 0,
	ARTICUNO: 0,
	ZAPDOS: 0,
	MOLTRES: 0,
	DRATINI: 0,
	DRAGONAIR: 0,
	DRAGONITE: 0,
	MEWTWO: 0,
	MEW: 0,
	CHIKORITA: 0,
	BAYLEEF: 0,
	MEGANIUM: 0,
	CYNDAQUIL: 0,
	QUILAVA: 0,
	TYPHLOSION: 0,
	TOTODILE: 0,
	CROCONAW: 0,
	FERALIGATR: 0,
	SENTRET: 0,
	FURRET: 0,
	HOOTHOOT: 0,
	NOCTOWL: 0,
	LEDYBA: 0,
	LEDIAN: 0,
	SPINARAK: 0,
	ARIADOS: 0,
	CROBAT: 0,
	CHINCHOU: 0,
	LANTURN: 0,
	PICHU: 0,
	CLEFFA: 0,
	IGGLYBUFF: 0,
	TOGEPI: 0,
	TOGETIC: 0,
	NATU: 0,
	XATU: 0,
	MAREEP: 0,
	FLAAFFY: 0,
	AMPHAROS: 0,
	BELLOSSOM: 0,
	MARILL: 0,
	AZUMARILL: 0,
	SUDOWOODO: 0,
	POLITOAD: 0,
	HOPPIP: 0,
	SKIPLOOM: 0,
	JUMPLUFF: 0,
	AIPOM: 0,
	SUNKERN: 0,
	SUNFLORA: 0,
	YANMA: 0,
	WOOPER: 0,
	QUAGSIRE: 0,
	ESPEON: 0,
	UMBREON: 0,
	MURKROW: 0,
	SLOWKING: 0,
	MISDREAVUS: 0,
	UNOWN: 0,
	WOBBUFFET: 0,
	GIRAFARIG: 0,
	PINECO: 0,
	FORRETRESS: 0,
	DUNSPARCE: 0,
	GLIGAR: 0,
	STEELIX: 0,
	SNUBBULL: 0,
	GRANBULL: 0,
	QWILFISH: 0,
	SCIZOR: 0,
	SHUCKLE: 0,
	HERACROSS: 0,
	SNEASEL: 0,
	TEDDIURSA: 0,
	URSARING: 0,
	SLUGMA: 0,
	MAGCARGO: 0,
	SWINUB: 0,
	PILOSWINE: 0,
	CORSOLA: 0,
	REMORAID: 0,
	OCTILLERY: 0,
	DELIBIRD: 0,
	MANTINE: 0,
	SKARMORY: 0,
	HOUNDOUR: 0,
	HOUNDOOM: 0,
	KINGDRA: 0,
	PHANPY: 0,
	DONPHAN: 0,
	PORYGON2: 0,
	STANTLER: 0,
	SMEARGLE: 0,
	TYROGUE: 0,
	HITMONTOP: 0,
	SMOOCHUM: 0,
	ELEKID: 0,
	MAGBY: 0,
	MILTANK: 0,
	BLISSEY: 0,
	RAIKOU: 0,
	ENTEI: 0,
	SUICUNE: 0,
	LARVITAR: 0,
	PUPITAR: 0,
	TYRANITAR: 0,
	LUGIA: 0,
	HO_OH: 0,
	CELEBI: 0,
	TREECKO: 0,
	GROVYLE: 0,
	SCEPTILE: 0,
	TORCHIC: 0,
	COMBUSKEN: 0,
	BLAZIKEN: 0,
	MUDKIP: 0,
	MARSHTOMP: 0,
	SWAMPERT: 0,
	POOCHYENA: 0,
	MIGHTYENA: 0,
	ZIGZAGOON: 0,
	LINOONE: 0,
	WURMPLE: 0,
	SILCOON: 0,
	BEAUTIFLY: 0,
	CASCOON: 0,
	DUSTOX: 0,
	LOTAD: 0,
	LOMBRE: 0,
	LUDICOLO: 0,
	SEEDOT: 0,
	NUZLEAF: 0,
	SHIFTRY: 0,
	TAILLOW: 0,
	SWELLOW: 0,
	WINGULL: 0,
	PELIPPER: 0,
	RALTS: 0,
	KIRLIA: 0,
	GARDEVOIR: 0,
	SURSKIT: 0,
	MASQUERAIN: 0,
	SHROOMISH: 0,
	BRELOOM: 0,
	SLAKOTH: 0,
	VIGOROTH: 0,
	SLAKING: 0,
	NINCADA: 0,
	NINJASK: 0,
	SHEDINJA: 0,
	WHISMUR: 0,
	LOUDRED: 0,
	EXPLOUD: 0,
	MAKUHITA: 0,
	HARIYAMA: 0,
	AZURILL: 0,
	NOSEPASS: 0,
	SKITTY: 0,
	DELCATTY: 0,
	SABLEYE: 0,
	MAWILE: 0,
	ARON: 0,
	LAIRON: 0,
	AGGRON: 0,
	MEDITITE: 0,
	MEDICHAM: 0,
	ELECTRIKE: 0,
	MANECTRIC: 0,
	PLUSLE: 0,
	MINUN: 0,
	VOLBEAT: 0,
	ILLUMISE: 0,
	ROSELIA: 0,
	GULPIN: 0,
	SWALOT: 0,
	CARVANHA: 0,
	SHARPEDO: 0,
	WAILMER: 0,
	WAILORD: 0,
	NUMEL: 0,
	CAMERUPT: 0,
	TORKOAL: 0,
	SPOINK: 0,
	GRUMPIG: 0,
	SPINDA: 0,
	TRAPINCH: 0,
	VIBRAVA: 0,
	FLYGON: 0,
	CACNEA: 0,
	CACTURNE: 0,
	SWABLU: 0,
	ALTARIA: 0,
	ZANGOOSE: 0,
	SEVIPER: 0,
	LUNATONE: 0,
	SOLROCK: 0,
	BARBOACH: 0,
	WHISCASH: 0,
	CORPHISH: 0,
	CRAWDAUNT: 0,
	BALTOY: 0,
	CLAYDOL: 0,
	LILEEP: 0,
	CRADILY: 0,
	ANORITH: 0,
	ARMALDO: 0,
	FEEBAS: 0,
	MILOTIC: 0,
	CASTFORM: 0,
	KECLEON: 0,
	SHUPPET: 0,
	BANETTE: 0,
	DUSKULL: 0,
	DUSCLOPS: 0,
	TROPIUS: 0,
	CHIMECHO: 0,
	ABSOL: 0,
	WYNAUT: 0,
	SNORUNT: 0,
	GLALIE: 0,
	SPHEAL: 0,
	SEALEO: 0,
	WALREIN: 0,
	CLAMPERL: 0,
	HUNTAIL: 0,
	GOREBYSS: 0,
	RELICANTH: 0,
	LUVDISC: 0,
	BAGON: 0,
	SHELGON: 0,
	SALAMENCE: 0,
	BELDUM: 0,
	METANG: 0,
	METAGROSS: 0,
	REGIROCK: 0,
	REGICE: 0,
	REGISTEEL: 0,
	LATIAS: 0,
	LATIOS: 0,
	KYOGRE: 0,
	GROUDON: 0,
	RAYQUAZA: 0,
	JIRACHI: 0,
	DEOXYS: 0,
	total: function() {
		return this.BULBASAUR 
		+ this.IVYSAUR 
		+ this.VENUSAUR 
		+ this.CHARMANDER 
		+ this.CHARMELEON 
		+ this.CHARIZARD 
		+ this.SQUIRTLE 
		+ this.WARTORTLE 
		+ this.BLASTOISE 
		+ this.CATERPIE 
		+ this.METAPOD 
		+ this.BUTTERFREE 
		+ this.WEEDLE 
		+ this.KAKUNA 
		+ this.BEEDRILL 
		+ this.PIDGEY 
		+ this.PIDGEOTTO 
		+ this.PIDGEOT 
		+ this.RATTATA 
		+ this.RATICATE
		+ this.SPEAROW
		+ this.FEAROW
		+ this.EKANS
		+ this.ARBOK
		+ this.PIKACHU
		+ this.RAICHU
		+ this.SANDSHREW
		+ this.SANDSLASH
		+ this.NIDORAN_FEMALE
		+ this.NIDORINA
		+ this.NIDOQUEEN
		+ this.NIDORAN_MALE
		+ this.NIDORINO
		+ this.NIDOKING
		+ this.CLEFAIRY
		+ this.CLEFABLE
		+ this.VULPIX
		+ this.NINETALES
		+ this.JIGGLYPUFF
		+ this.WIGGLYTUFF
		+ this.ZUBAT
		+ this.GOLBAT
		+ this.ODDISH
		+ this.GLOOM
		+ this.VILEPLUME
		+ this.PARAS
		+ this.PARASECT
		+ this.VENONAT
		+ this.VENOMOTH
		+ this.DIGLETT
		+ this.DUGTRIO
		+ this.MEOWTH
		+ this.PERSIAN
		+ this.PSYDUCK
		+ this.GOLDUCK
		+ this.MANKEY
		+ this.PRIMEAPE
		+ this.GROWLITHE
		+ this.ARCANINE
		+ this.POLIWAG
		+ this.POLIWHIRL
		+ this.POLIWRATH
		+ this.ABRA
		+ this.KADABRA
		+ this.ALAKAZAM
		+ this.MACHOP
		+ this.MACHOKE
		+ this.MACHAMP
		+ this.BELLSPROUT
		+ this.WEEPINBELL
		+ this.VICTREEBELL
		+ this.TENTACOOL
		+ this.TENTACRUEL
		+ this.GEODUDE
		+ this.GRAVELER
		+ this.GOLEM
		+ this.PONYTA
		+ this.RAPIDASH
		+ this.SLOWPOKE
		+ this.SLOWBRO
		+ this.MAGNEMITE
		+ this.MAGNETON
		+ this.FARFETCH_D
		+ this.DODUO
		+ this.DODRIO
		+ this.SEEL
		+ this.DEWGONG
		+ this.GRIMER
		+ this.MUK
		+ this.SHELLDER
		+ this.CLOYSTER
		+ this.GASTLY
		+ this.HAUNTER
		+ this.GENGAR
		+ this.ONIX
		+ this.DROWZEE
		+ this.HYPNO
		+ this.KRABBY
		+ this.KINGLER
		+ this.VOLTORB
		+ this.ELECTRODE
		+ this.EXEGGCUTE
		+ this.EXEGGUTOR
		+ this.CUBONE
		+ this.MAROWAK
		+ this.HITMONLEE
		+ this.HITMONCHAN
		+ this.LICKITUNG
		+ this.KOFFING
		+ this.WEEZING
		+ this.RHYHORN
		+ this.RHYDON
		+ this.CHANSEY
		+ this.TANGELA
		+ this.KANGASKHAN
		+ this.HORSEA
		+ this.SEADRA
		+ this.GOLDEEN
		+ this.SEAKING
		+ this.STARYU
		+ this.STARMIE
		+ this.MR_MIME
		+ this.SCYTHER
		+ this.JYNX
		+ this.ELECTABUZZ
		+ this.MAGMAR
		+ this.PINSIR
		+ this.TAUROS
		+ this.MAGIKARP
		+ this.GYARADOS
		+ this.LAPRAS
		+ this.DITTO
		+ this.EEVEE
		+ this.VAPOREON
		+ this.JOLTEON
		+ this.FLAREON
		+ this.PORYGON
		+ this.OMANYTE
		+ this.OMASTAR
		+ this.KABUTO
		+ this.KABUTOPS
		+ this.AERODACTYL
		+ this.SNORLAX
		+ this.ARTICUNO
		+ this.ZAPDOS
		+ this.MOLTRES
		+ this.DRATINI
		+ this.DRAGONAIR
		+ this.DRAGONITE
		+ this.MEWTWO
		+ this.MEW
		+ this.CHIKORITA
		+ this.BAYLEEF
		+ this.MEGANIUM
		+ this.CYNDAQUIL
		+ this.QUILAVA
		+ this.TYPHLOSION
		+ this.TOTODILE
		+ this.CROCONAW
		+ this.FERALIGATR
		+ this.SENTRET
		+ this.FURRET
		+ this.HOOTHOOT
		+ this.NOCTOWL
		+ this.LEDYBA
		+ this.LEDIAN
		+ this.SPINARAK
		+ this.ARIADOS
		+ this.CROBAT
		+ this.CHINCHOU
		+ this.LANTURN
		+ this.PICHU
		+ this.CLEFFA
		+ this.IGGLYBUFF
		+ this.TOGEPI
		+ this.TOGETIC
		+ this.NATU
		+ this.XATU
		+ this.MAREEP
		+ this.FLAAFFY
		+ this.AMPHAROS
		+ this.BELLOSSOM
		+ this.MARILL
		+ this.AZUMARILL
		+ this.SUDOWOODO
		+ this.POLITOAD
		+ this.HOPPIP
		+ this.SKIPLOOM
		+ this.JUMPLUFF
		+ this.AIPOM
		+ this.SUNKERN
		+ this.SUNFLORA
		+ this.YANMA
		+ this.WOOPER
		+ this.QUAGSIRE
		+ this.ESPEON
		+ this.UMBREON
		+ this.MURKROW
		+ this.SLOWKING
		+ this.MISDREAVUS
		+ this.UNOWN
		+ this.WOBBUFFET
		+ this.GIRAFARIG
		+ this.PINECO
		+ this.FORRETRESS
		+ this.DUNSPARCE
		+ this.GLIGAR
		+ this.STEELIX
		+ this.SNUBBULL
		+ this.GRANBULL
		+ this.QWILFISH
		+ this.SCIZOR
		+ this.SHUCKLE
		+ this.HERACROSS
		+ this.SNEASEL
		+ this.TEDDIURSA
		+ this.URSARING
		+ this.SLUGMA
		+ this.MAGCARGO
		+ this.SWINUB
		+ this.PILOSWINE
		+ this.CORSOLA
		+ this.REMORAID
		+ this.OCTILLERY
		+ this.DELIBIRD
		+ this.MANTINE
		+ this.SKARMORY
		+ this.HOUNDOUR
		+ this.HOUNDOOM
		+ this.KINGDRA
		+ this.PHANPY
		+ this.DONPHAN
		+ this.PORYGON2
		+ this.STANTLER
		+ this.SMEARGLE
		+ this.TYROGUE
		+ this.HITMONTOP
		+ this.SMOOCHUM
		+ this.ELEKID
		+ this.MAGBY
		+ this.MILTANK
		+ this.BLISSEY
		+ this.RAIKOU
		+ this.ENTEI
		+ this.SUICUNE
		+ this.LARVITAR
		+ this.PUPITAR
		+ this.TYRANITAR
		+ this.LUGIA
		+ this.HO_OH
		+ this.CELEBI
		+ this.TREECKO
		+ this.GROVYLE
		+ this.SCEPTILE
		+ this.TORCHIC
		+ this.COMBUSKEN
		+ this.BLAZIKEN
		+ this.MUDKIP
		+ this.MARSHTOMP
		+ this.SWAMPERT
		+ this.POOCHYENA
		+ this.MIGHTYENA
		+ this.ZIGZAGOON
		+ this.LINOONE
		+ this.WURMPLE
		+ this.SILCOON
		+ this.BEAUTIFLY
		+ this.CASCOON
		+ this.DUSTOX
		+ this.LOTAD
		+ this.LOMBRE
		+ this.LUDICOLO
		+ this.SEEDOT
		+ this.NUZLEAF
		+ this.SHIFTRY
		+ this.TAILLOW
		+ this.SWELLOW
		+ this.WINGULL
		+ this.PELIPPER
		+ this.RALTS
		+ this.KIRLIA
		+ this.GARDEVOIR
		+ this.SURSKIT
		+ this.MASQUERAIN
		+ this.SHROOMISH
		+ this.BRELOOM
		+ this.SLAKOTH
		+ this.VIGOROTH
		+ this.SLAKING
		+ this.NINCADA
		+ this.NINJASK
		+ this.SHEDINJA
		+ this.WHISMUR
		+ this.LOUDRED
		+ this.EXPLOUD
		+ this.MAKUHITA
		+ this.HARIYAMA
		+ this.AZURILL
		+ this.NOSEPASS
		+ this.SKITTY
		+ this.DELCATTY
		+ this.SABLEYE
		+ this.MAWILE
		+ this.ARON
		+ this.LAIRON
		+ this.AGGRON
		+ this.MEDITITE
		+ this.MEDICHAM
		+ this.ELECTRIKE
		+ this.MANECTRIC
		+ this.PLUSLE
		+ this.MINUN
		+ this.VOLBEAT
		+ this.ILLUMISE
		+ this.ROSELIA
		+ this.GULPIN
		+ this.SWALOT
		+ this.CARVANHA
		+ this.SHARPEDO
		+ this.WAILMER
		+ this.WAILORD
		+ this.NUMEL
		+ this.CAMERUPT
		+ this.TORKOAL
		+ this.SPOINK
		+ this.GRUMPIG
		+ this.SPINDA
		+ this.TRAPINCH
		+ this.VIBRAVA
		+ this.FLYGON
		+ this.CACNEA
		+ this.CACTURNE
		+ this.SWABLU
		+ this.ALTARIA
		+ this.ZANGOOSE
		+ this.SEVIPER
		+ this.LUNATONE
		+ this.SOLROCK
		+ this.BARBOACH
		+ this.WHISCASH
		+ this.CORPHISH
		+ this.CRAWDAUNT
		+ this.BALTOY
		+ this.CLAYDOL
		+ this.LILEEP
		+ this.CRADILY
		+ this.ANORITH
		+ this.ARMALDO
		+ this.FEEBAS
		+ this.MILOTIC
		+ this.CASTFORM
		+ this.KECLEON
		+ this.SHUPPET
		+ this.BANETTE
		+ this.DUSKULL
		+ this.DUSCLOPS
		+ this.TROPIUS
		+ this.CHIMECHO
		+ this.ABSOL
		+ this.WYNAUT
		+ this.SNORUNT
		+ this.GLALIE
		+ this.SPHEAL
		+ this.SEALEO
		+ this.WALREIN
		+ this.CLAMPERL
		+ this.HUNTAIL
		+ this.GOREBYSS
		+ this.RELICANTH
		+ this.LUVDISC
		+ this.BAGON
		+ this.SHELGON
		+ this.SALAMENCE
		+ this.BELDUM
		+ this.METANG
		+ this.METAGROSS
		+ this.REGIROCK
		+ this.REGICE
		+ this.REGISTEEL
		+ this.LATIAS
		+ this.LATIOS
		+ this.KYOGRE
		+ this.GROUDON
		+ this.RAYQUAZA
		+ this.JIRACHI
		+ this.DEOXYS;
	}
};
